version: '3.7'
services:
  portfolio-www:
    image: portfolio-www:latest
    networks:
      - portfolio
    deploy:
      replicas: 3

  portfolio-admin:
    image: portfolio-admin
    networks:
      - portfolio
    deploy:
      replicas: 1
  
  portfolio-api:
    image: portfolio-api
    depends_on:
      - portfolio-db
    networks:
      - portfolio
    deploy:
      replicas: 3

  portfolio-nginx:
    # depends_on:
    #   - portfolio-www
    #   - portfolio-admin
    #   - portfolio-api
    image: portfolio-nginx
    volumes:
      - portfolio-nginx:/etc/nginx
    networks:
      - portfolio
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
      - ./dhparam:/etc/nginx/dhparam
      - ./conf.d:/etc/nginx/conf.d
      - ./server-admin:/etc/nginx/server-admin
      - ./server-www:/etc/nginx/server-www
      - ./server-api:/etc/nginx/server-api

  portfolio-certbot:
    depends_on:
      - portfolio-nginx
    image: portfolio-certbot
    # command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email sungryeolp@gmail.com --agree-tos --no-eff-email -d 





networks:
  - portfolio
volumes:
  - portfolio-nginx

#       nginx:
#     image: lvup-nginx:latest
#     env_file:
#       - .env.production
#     # build:
#     #   context: .
#     #   dockerfile: nginx.prod.Dockerfile
#     depends_on:
#       - node
#     ports:
#       - '80:80'
#     volumes:
#       - lvupfront-node-dist:/home/node/app/dist
#     networks:
#       - lvup-front

#   node:
#     image: lvup-node:latest
#     # build:
#     #   context: .
#     #  dockerfile: node.prod.Dockerfile
#     user: node
#     volumes:
#       - ./:/home/node/app
#       - lvupfront-node-dist:/home/node/app/dist
#     networks:
#       - lvup-front

# networks:
#   lvup-front:
# volumes:
#   lvupfront-node-dist: